from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class AuthorAffiliation(BaseModel):
    author_id: Optional[str] = Field(default=None, description="Unique Author Identifier (e.g., OpenAlex or ORCID)")
    author_name: str = Field(default="Unknown", description="Full name of the academic author")
    institution_id: Optional[str] = Field(default=None, description="Unique Institution Identifier")
    institution_name: Optional[str] = Field(default=None, description="Raw institution or university name")
    normalized_department: Optional[str] = Field(
        default=None, 
        description="Normalized faculty or department name for standardized UI facet filtering"
    )


class ExpertiseMetadata(BaseModel):
    primary_domain: Optional[str] = Field(
        default="General Academic",
        description="Primary engineering or research domain (e.g., Civil Engineering, Quantum Computing)"
    )
    methodologies: List[str] = Field(
        default_factory=list,
        description="Specific methodologies, algorithms, or analytical frameworks utilized"
    )
    core_tools: List[str] = Field(
        default_factory=list,
        description="Software, computational libraries, or physical instruments utilized"
    )


class AcademicPublication(BaseModel):
    openalex_id: str = Field(description="Unique primary key identifier from source provider")
    doi: Optional[str] = Field(default=None, description="Digital Object Identifier")
    title: str = Field(description="Publication title")
    publication_year: Optional[int] = Field(default=None, description="Four-digit publication year")
    publication_date: Optional[str] = Field(default=None, description="Publication date in ISO format (YYYY-MM-DD)")
    is_open_access: bool = Field(default=False, description="Open access accessibility indicator")
    pdf_url: Optional[str] = Field(default=None, description="Direct URL to official open-access PDF stream")
    landing_page_url: Optional[str] = Field(default=None, description="Publisher or DOI landing page URL")
    authors: List[AuthorAffiliation] = Field(default_factory=list, description="List of authors and academic affiliations")
    abstract_inverted_index: Optional[Dict[str, Any]] = Field(default=None, description="Raw inverted index mapping from source API")
    reconstructed_abstract: Optional[str] = Field(default=None, description="Cleaned, linearly reconstructed abstract text")
    full_text: Optional[str] = Field(default=None, description="Extracted full-text content from PDF stream")
    
    # LLM-Assisted Enrichment Fields (Section 4 Compliance)
    executive_summary: Optional[str] = Field(
        default=None, 
        description="Concise 2-3 sentence business-friendly summary generated by LLM"
    )
    expertise_metadata: Optional[ExpertiseMetadata] = Field(
        default=None, 
        description="Structured domain expertise, methodologies, and core tools extracted by LLM"
    )
    hyde_questions: List[str] = Field(
        default_factory=list, 
        description="2-3 hypothetical user questions (HyDE) answered by this publication"
    )
    
    concepts: List[str] = Field(default_factory=list, description="Academic concepts or domain keywords")
    cited_by_count: int = Field(default=0, description="Total citation metric count")

    def reconstruct_abstract(self) -> Optional[str]:
        """Safely reconstructs readable abstract from OpenAlex inverted index mapping."""
        if not self.abstract_inverted_index or not isinstance(self.abstract_inverted_index, dict):
            return None
        
        try:
            index_map = {}
            for word, positions in self.abstract_inverted_index.items():
                if isinstance(positions, list):
                    for pos in positions:
                        if isinstance(pos, int):
                            index_map[pos] = word
            
            if not index_map:
                return None

            sorted_positions = sorted(index_map.keys())
            self.reconstructed_abstract = " ".join([index_map[pos] for pos in sorted_positions])
            return self.reconstructed_abstract
        except Exception:
            return None


if __name__ == "__main__":
    # Test execution schema initialization
    pub = AcademicPublication(
        openalex_id="https://openalex.org/W123456789",
        title="Sample TU Delft Quantum Engineering Paper",
        abstract_inverted_index={"Quantum": [0], "computing": [1], "advancements": [2]}
    )
    pub.reconstruct_abstract()
    print("[SUCCESS] Schema initialized. Reconstructed Abstract:", pub.reconstructed_abstract)
